CREATE TABLE usuario(
id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nome VARCHAR(254),
email VARCHAR(254),
senha varchar(254),
mao_obra varchar(254)
)


ALTER TABLE usuario ADD tentativas INTEGER;
ALTER TABLE USUARIO DROP mao_obra
ALTER TABLE usuario ADD mao_obra NUMERIC(6,2);


SELECT * FROM USUARIO u 

CREATE TABLE senhas_utilizadas(
id_senhas_utilizadas INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
id_usuario INTEGER,
senha varchar(254),

 CONSTRAINT FK_SENHA_USUARIO
 FOREIGN KEY (ID_USUARIO) REFERENCES usuario(id_usuario)

)

SELECT * FROM SENHAS_UTILIZADAS 