CREATE TABLE usuario(
id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nome VARCHAR(254),
email VARCHAR(254),
senha varchar(254),
mao_obra NUMERIC(4,3)
)

ALTER TABLE usuario ADD tentativas INTEGER;